'//////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' DO NOT MODIFY THIS FILE! It is regenerated by the designer.
' All your modifications will be lost!
' http://www.ranorex.com
'
'//////////////////////////////////////////////////////////////////////////////

Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Drawing
Imports Ranorex
Imports Ranorex.Core
Imports Ranorex.Core.Repository
Imports Ranorex.Core.Testing

Namespace RemoteTest
    ''' <summary>
    ''' The class representing the RemoteTestRepository element repository.
    ''' </summary>
        <System.CodeDom.Compiler.GeneratedCode("Ranorex", Global.Ranorex.Core.Constants.CodeGenVersion), _
    RepositoryFolder("3bb8e208-fc40-4153-a856-88d38a8bb993")> _
    Partial Public Class RemoteTestRepository
        Inherits RepoGenBaseFolder
    
        Shared _instance As RemoteTestRepository = New RemoteTestRepository()
        Dim _applicationundertest As RemoteTestRepositoryFolders.ApplicationUnderTestAppFolder
    
        ''' <summary>
        ''' Repository class constructor.
        ''' </summary>
        Public Sub New()
            MyBase.New("RemoteTestRepository", "/", Nothing, 0, False,"3bb8e208-fc40-4153-a856-88d38a8bb993", ".\RepositoryImages\RemoteTestRepository3bb8e208.rximgres")
            _applicationundertest = New RemoteTestRepositoryFolders.ApplicationUnderTestAppFolder(Me)
        End Sub
    
        ''' <summary>
        ''' Gets the singleton class instance representing the RemoteTestRepository element repository.
        ''' </summary>
        <RepositoryFolder("3bb8e208-fc40-4153-a856-88d38a8bb993")> _
        Public Shared ReadOnly Property Instance() As RemoteTestRepository
            Get
                Return _instance
            End Get
        End Property

#Region "Variables"
#End Region

        ''' <summary>
        ''' The Self item info.
        ''' </summary>
        <RepositoryItemInfo("3bb8e208-fc40-4153-a856-88d38a8bb993")> _
        Public Overridable ReadOnly Property SelfInfo() As RepoItemInfo
            Get
                Return _selfInfo
            End Get
        End Property
    
        ''' <summary>
        ''' The ApplicationUnderTest folder.
        ''' </summary>
        <RepositoryFolder("7fc4e004-6c21-4302-a09f-d83f79817c25")> _
        Public Overridable ReadOnly Property ApplicationUnderTest As RemoteTestRepositoryFolders.ApplicationUnderTestAppFolder
            Get
                Return _applicationundertest
            End Get
        End Property
    End Class
    
    ''' <summary>
    ''' Inner folder classes.
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCode("Ranorex", Global.Ranorex.Core.Constants.CodeGenVersion)> _
    Partial Public Class RemoteTestRepositoryFolders
    
        ''' <summary>
        ''' The ApplicationUnderTestAppFolder folder.
        ''' </summary>
        <RepositoryFolder("7fc4e004-6c21-4302-a09f-d83f79817c25")> _
        Partial Public Class ApplicationUnderTestAppFolder
            Inherits RepoGenBaseFolder
    
    
            ''' <summary>
            ''' Creates a new ApplicationUnderTest  folder.
            ''' </summary>
            Public Sub New(parentFolder As RepoGenBaseFolder)
                MyBase.New("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, Nothing, False, "7fc4e004-6c21-4302-a09f-d83f79817c25", ".\RepositoryImages\RemoteTestRepository3bb8e208.rximgres")
            End Sub

            ''' <summary>
            ''' The Self item.
            ''' </summary>
            <RepositoryItem("7fc4e004-6c21-4302-a09f-d83f79817c25")> _
            Public Overridable ReadOnly Property Self As Ranorex.WebDocument
                Get
                    Return _selfInfo.CreateAdapter(Of Ranorex.WebDocument)(True)
                End Get
            End Property

            ''' <summary>
            ''' The Self item info.
            ''' </summary>
            <RepositoryItemInfo("7fc4e004-6c21-4302-a09f-d83f79817c25")> _
            Public Overridable ReadOnly Property SelfInfo As RepoItemInfo
                Get
                    Return _selfInfo
                End Get
            End Property
        End Class
    End Class
End Namespace
